---
- name: Install apache2
  apt:
    name: ['apache2', 'libapache2-mod-wsgi-py3']
    state: latest

- name: Change apache2 ports from 80 to 8080
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen 80'
    line: 'Listen 8080'

- name: Create configuration files
  template:
    src: micro.conf
    dest: "/etc/apache2/sites-enabled/000_micro.conf"
    owner: www-data
    group: www-data
    mode: 0644
  register: configuration_files_status

- name: Reload apache2 service
  service:
    name: apache2
    state: reloaded
  when:
    - configuration_files_status.changed
    - ansible_check_mode == False
