---
- name: Create the microservice directory
  file:
    path: /opt/microservice
    state: directory
    mode: '0755'

- name: Upload microservice files
  template:
    src: '{{ item.src }}'
    dest: /opt/microservice
  with_filetree: '../templates'
  when: item.state == 'file'

- name: Upload systemd config
  template:
    src: micro.service
    dest: /etc/systemd/system

- name: Upload nginx config
  template:
    src: micro.conf
    dest: /etc/nginx/sites-enabled

- name: Install pip3
  apt:
    name: python3-pip

- name: Install virtualenv
  pip:
    name: virtualenv
    executable: pip3

- name: Install pip requirements
  pip:
    requirements: "/opt/microservice/requirements.txt"
    virtualenv: "/opt/microservice/env"
    virtualenv_python: python3

- name: Check ownership of project directory
  stat:
    path: "{{ project_path }}"
  register: project_path_stats

- name: Set owner and group on project directory
  file:
    path: "{{ project_path }}"
    owner: www-data
    group: www-data
    recurse: true
  when: project_path_stats.stat.pw_name != 'www-data'

- name: Restart the micro service
  systemd:
    name: micro
    enabled: yes
    state: restarted

- name: Restart nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted
