---
- name: Create the microservice directory
  file:
    path: '{{ project_path }}/logs'
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Upload microservice files
  template:
    src: '{{ item.src }}'
    dest: '{{ project_path }}'
  with_filetree: '../templates'
  when: item.state == 'file'
  tags:
    - upload

- name: Upload nginx config
  template:
    src: micro.nginx.conf
    dest: /etc/nginx/sites-available/default

- name: Install pip3
  apt:
    name: python3-pip
    state: latest

- name: Install virtualenv
  pip:
    name: virtualenv
    executable: pip3

- name: Install pip requirements
  pip:
    requirements: '{{ project_path }}/requirements.txt'
    virtualenv: '{{ project_path }}/env'
    virtualenv_python: python3

- name: Check ownership of project directory
  stat:
    path: '{{ project_path }}'
  register: project_path_stats

- name: Set owner and group on project directory
  file:
    path: '{{ project_path }}'
    owner: www-data
    group: www-data
    recurse: true
  when: project_path_stats.stat.pw_name != 'www-data'

- name: Restart nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: Restart apache2
  systemd:
    name: apache2
    enabled: yes
    state: restarted
