---
- hosts: server
  gather_facts: false
  roles:
      - role: patch
        tags: patch
      - role: apache2
        tags: apache2
      - role: nginx
        tags: nginx
      - role: rbase
        tags: rbase
      - role: micro
        tags: micro

