---
- name: Add the R repository GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

# Add specified repository into sources list.
- name: Add the R repository
  apt_repository:
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/
    state: present

- name: Create an R profile
  lineinfile:
    path: /root/.Rprofile
    line: options(Ncpus = 6)
    create: yes

- name: Install R base and supporting libs
  apt:
    name: "{{ packages }}"
    state: latest
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 86400
  vars:
    packages:
    - r-base
    - r-base-core
    - build-essential
    - libcurl4-gnutls-dev
    - libxml2-dev
    - libssl-dev
    - default-jdk
