---
- name: Add the R repository GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

# Add specified repository into sources list.
- name: Add the R repository
  apt_repository:
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/
    state: present

- name: Install R-base
  apt:
    name:
      - r-base
      - r-base-core
    state: latest
    autoclean: yes
    autoremove: yes
    only_upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install R libraries
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('http://ftp.heanet.ie/mirrors/cran.r-project.org/')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - rdrop2
    - rJava
    - tidyverse
    - httr
    - imager
    - jsonlite
    - dplyr
    - zoo
    - qdap
    - tm
    - NLP
    - openNLP
    - zoo
    - data.table
    - jsonlite
    - ggplot2
    - SnowballC
    - RDRPOSTagger
    - tokenizers
    - tidytext
